[metadata]
name = "example 4 gateway policy 1"
parents = ["example 4 gateway class policy 2", "example 4 gateway class policy 1"]

[policyMetadata]
type = "default"
strategy = "merge"

[spec]
field_b = "b"
