[metadata]
name = "example 5 service policy 1"
parents = ["example 5 http policy 1", "example 5 http policy 2", "example 5 http policy 3"]

[policyMetadata]
type = "default"
strategy = "merge"

[spec]
field_d = "service default"
field_f = "f"