[metadata]
name = "example 1 service policy 1"
parents = ["example 1 http policy 2", "example 1 http policy 1"]

[policyMetadata]
type = "default"
strategy = "merge"

[spec]
field_d = "service default"
field_e = "e"
