[metadata]
name = "example 6 service policy 1"
parents = ["example 6 http policy 1", "example 6 http policy 2"]

[policyMetadata]
type = "default"
strategy = "merge"

[spec]
field_d = "service default"